# Practice Assignments

In [152]:
import numpy as np
import pprint

import warnings
warnings.filterwarnings('ignore')

In [1]:
# (Common data for 1,2,3)
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

## Q1

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
c_vectorizer = CountVectorizer()
X_c = c_vectorizer.fit_transform(text_data)

X_c.shape

(9, 99)

## Q2

In [44]:
c_vectorizer2 = CountVectorizer(min_df=2)
X_c2 = c_vectorizer2.fit_transform(text_data)

X_c2.shape

(9, 20)

## Q3

In [47]:
c_vectorizer.vocabulary_

{'metaverse': 51, 'is': 43, 'network': 53, 'of': 55, '3d': 2, 'virtual': 94, 'worlds': 98, 'focused': 26, 'on': 57, 'social': 77, 'connection': 15, 'in': 35, 'futurism': 29, 'and': 5, 'science': 71, 'fiction': 25, 'the': 86, 'term': 84, 'often': 56, 'described': 18, 'as': 7, 'hypothetical': 34, 'iteration': 44, 'internet': 41, 'single': 75, 'universal': 88, 'world': 97, 'that': 85, 'facilitated': 23, 'by': 12, 'use': 90, 'augmented': 8, 'reality': 68, 'headsets': 33, 'has': 31, 'its': 46, 'origins': 58, '1992': 1, 'novel': 54, 'snow': 76, 'crash': 17, 'portmanteau': 62, 'meta': 50, 'universe': 89, 'various': 92, 'metaverses': 52, 'have': 32, 'been': 9, 'developed': 19, 'for': 27, 'popular': 61, 'such': 81, 'platforms': 60, 'like': 48, 'second': 72, 'life': 47, 'some': 78, 'iterations': 45, 'involve': 42, 'integration': 39, 'between': 10, 'physical': 59, 'spaces': 79, 'economies': 21, 'including': 36, 'significant': 74, 'interest': 40, 'advancing': 4, 'technology': 83, 'seen': 73, 'cons

In [48]:
c_vectorizer2.vocabulary_

{'metaverse': 7, 'is': 6, 'of': 9, 'virtual': 18, 'social': 13, 'in': 5, 'and': 0, 'science': 12, 'fiction': 2, 'the': 15, 'term': 14, 'often': 10, 'as': 1, 'world': 19, 'use': 16, 'reality': 11, 'has': 4, 'various': 17, 'metaverses': 8, 'for': 3}

## Q4

In [49]:
docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

c_vectorizer3 = CountVectorizer()
X_c3 = c_vectorizer3.fit_transform(docs)

X_c3.shape

(3, 10)

In [50]:
X_c3.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]], dtype=int64)

In [51]:
c_vectorizer3.vocabulary_

{'this': 9, 'is': 3, 'the': 7, 'first': 2, 'question': 5, 'document': 1, 'second': 6, 'and': 0, 'third': 8, 'one': 4}

## Q5

In [52]:
X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]]) 
p= np.asarray([[0,0,0]]) 
k=1 

def k_closest(X, p, k):
    from sklearn.neighbors import NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=k).fit(X)
    dist, indx = nbrs.kneighbors(p)
    return indx, X[indx]

k_closest(X, p, k)

(array([[2]], dtype=int64), array([[[20, 47, 88]]]))

## Q6

In [71]:
X0 = np.array([1,0,0,0]) 
X= np.asarray([[1, 0, 0,0], [0, 1, 1,1], [1,2,0,0]])
p= 2 

def distance(X0, X, p):
    X00 = np.ones((len(X), len(X[0]))) * X0
    d = np.sum(np.power(np.abs(X-X00), p), axis=1)
    return np.power(d, 1/p)

distance(X0, X, p)

array([0., 2., 2.])

## Q7 to 11

In [91]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, f1_score

X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

## Q7

In [78]:
X.shape

(1797, 64)

## Q8

In [79]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Q9

In [83]:
len(np.where(y==7)[0])

179

## Q10

In [93]:
pipe = make_pipeline(StandardScaler(), LogisticRegression(multi_class='multinomial', solver='sag'))
pipe.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(multi_class='multinomial', solver='sag'))])

In [96]:
y_pred = pipe.predict(X_test)

accuracy_score(y_test, y_pred)

0.9666666666666667

## Q11

In [97]:
f1_score(y_test, y_pred, average='weighted')

0.966907732026411

# Graded Assignments

In [125]:
import pandas as pd
from sklearn.linear_model import SGDRegressor

### Step2

In [99]:
df = pd.read_csv('data_for_large_scale.csv')
df.head()

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0     -1.580     1.0500      1.060     -0.440      0.451    -0.0348   
1     -0.832    -0.8660     -1.340      0.138      1.180     0.7330   
2     -0.237     2.0900     -3.930      0.296      0.352    -0.5010   
3     -1.170    -1.1300     -1.090      1.120      0.312     0.1830   
4      0.260    -0.0273      0.925     -1.150     -1.390     0.0251   

   Feature-7  Feature-8  Feature-9  Feature-10  Target  
0      0.643     0.2650      0.268      -0.851    84.7  
1     -1.410     0.1350     -0.088      -1.550  -211.0  
2      0.961    -0.0287      1.820       0.938   -96.9  
3      0.448    -0.8190     -1.010      -1.080  -152.0  
4      0.627     0.0950     -0.280      -0.848   -57.7

### Step3 & 4

In [115]:
X, y = np.array(df.loc[:, df.columns != 'Target']), np.array(df.Target)

In [116]:
X, y

(array([[-1.58  ,  1.05  ,  1.06  , ...,  0.265 ,  0.268 , -0.851 ],
       [-0.832 , -0.866 , -1.34  , ...,  0.135 , -0.088 , -1.55  ],
       [-0.237 ,  2.09  , -3.93  , ..., -0.0287,  1.82  ,  0.938 ],
       ...,
       [ 0.509 , -0.322 ,  0.681 , ...,  0.727 , -1.94  , -2.01  ],
       [ 0.36  ,  1.25  ,  0.651 , ..., -0.367 , -1.28  , -1.1   ],
       [-0.86  , -0.601 ,  0.739 , ..., -0.483 , -1.38  ,  1.11  ]]), array([  84.7, -211. ,  -96.9, ...,  -80.2,  158. , -369. ]))

### Step5

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
X_train.shape, X_train

((63000, 10), array([[ 0.224 ,  0.631 ,  0.639 , ..., -1.54  ,  1.03  , -0.17  ],
       [-1.01  ,  0.118 ,  0.781 , ...,  0.7   , -0.249 , -1.05  ],
       [ 1.97  , -0.358 ,  0.297 , ..., -0.411 ,  0.214 , -1.23  ],
       ...,
       [ 1.3   , -0.828 , -0.369 , ..., -0.315 , -1.8   ,  0.678 ],
       [-0.977 ,  0.254 ,  0.582 , ..., -0.0417,  0.806 , -0.496 ],
       [-0.141 , -0.831 , -0.199 , ...,  0.186 ,  0.94  , -0.782 ]]))

### Step6

In [128]:
X_train_rshpd, y_train_rshpd = X_train.reshape(-1, 90, 10), y_train.reshape(-1, 90)
X_train_rshpd.shape, y_train_rshpd.shape

((700, 90, 10), (700, 90))

In [134]:
regressor = SGDRegressor(random_state=10)
i = 0
for X_trn, y_trn in zip(X_train_rshpd, y_train_rshpd):
    i+= 1
    regressor.partial_fit(X_trn, y_trn)
    if i == 5:
        print(i)
        print('regressor.coef_:', regressor.coef_)
        print('regressor.intercept_:', regressor.intercept_) 
        print('--------------------------------------------------------------')
print(i)    
print('regressor.coef_:', regressor.coef_)
print('regressor.intercept_:', regressor.intercept_)       

5
regressor.coef_: [38.10307994 16.55515794 55.39574282 39.59670638 56.0556394  54.99254453
 67.70253651 43.94562783 24.80852625 29.56006746]
regressor.intercept_: [-7.35495575]
--------------------------------------------------------------
700
regressor.coef_: [51.3212522  22.26535893 81.23762868 53.19615839 76.46565732 71.47204651
 93.45092409 51.92198178 30.03910055 40.95656774]
regressor.intercept_: [-0.0054532]


In [136]:
from sklearn.metrics import r2_score

y_pred = regressor.predict(X_test)
r2_score(y_test, y_pred)

0.9999919793766233

## Q6 to 8

In [197]:
sgd = SGDRegressor(random_state=10, warm_start=True)
sclr = StandardScaler()
sclr2 = StandardScaler()
# pipe = make_pipeline(sclr, sgd)

iter = 1
# df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt')
for df in pd.read_csv('3D_spatial_network.txt', chunksize=20000, iterator=True, header=None):
    X_trn, y_trn = df.iloc[:, 1:3], df.iloc[:, 3:]    
    sclr.partial_fit(X_trn) 
    iter+= 1
#     print(sclr.mean_)
#     print('---------------------------------------------------')

iter = 1
for df in pd.read_csv('3D_spatial_network.txt', chunksize=20000, iterator=True, header=None):
    X_trn, y_trn = df.iloc[:, 1:3], df.iloc[:, 3:] 
#     X_trn = sclr.transform(X_trn)
    sgd.fit(X_trn, y_trn) 
#     sclr2.partial_fit(X_trn) 
    if iter == 1:
        print(X_trn)
        print(y_trn)
    print('after iter #', iter)
    print(X_trn.mean(axis=0))
    print('sgd.coef_:', sgd.coef_)
    print('sgd.intercept_:', sgd.intercept_)  
    print('---------------------------------------------------')
    iter+=1
    
X_trn.mean(axis=0), X_trn.std(axis=0)        
# print('after iter #', iter)
# print(sclr2.mean_)
# print('sgd.coef_:', sgd.coef_)
# print('sgd.intercept_:', sgd.intercept_)      

              1          2
0      9.349849  56.740876
1      9.350188  56.740679
2      9.350549  56.740544
3      9.350806  56.740485
4      9.351053  56.740486
...         ...        ...
19995  9.841373  57.428327
19996  9.537111  57.211692
19997  9.537136  57.212001
19998  9.537276  57.212396
19999  9.537490  57.212913

[20000 rows x 2 columns]
               3
0      17.052772
1      17.614840
2      18.083536
3      18.279465
4      18.422974
...          ...
19995  20.299091
19996   9.242100
19997   9.267994
19998  10.219706
19999   9.052537

[20000 rows x 1 columns]
after iter # 1
1     9.615376
2    57.036769
dtype: float64
sgd.coef_: [  2160686.84071255 -11131128.80052789]
sgd.intercept_: [6.01967742e+08]
---------------------------------------------------
after iter # 2
1     9.769328
2    57.124693
dtype: float64
sgd.coef_: [  4411705.90117798 -15574224.68589523]
sgd.intercept_: [8.43460071e+08]
---------------------------------------------------
after iter # 3
1     9.73858

(1     9.721459
2    57.116715
dtype: float64, 1    0.665305
2    0.304291
dtype: float64)

In [200]:
sgd = SGDRegressor(random_state=10, warm_start=True, max_iter=7)
df = pd.read_csv('3D_spatial_network.txt', header=None)
X_trn, y_trn = df.iloc[:, 1:3], df.iloc[:, 3:] 
# X_trn = sclr.transform(X_trn)

sgd.fit(X_trn, y_trn)
print('sgd.coef_:', sgd.coef_)
print('sgd.intercept_:', sgd.intercept_)  

sgd.coef_: [  4621614.19896528 -19924694.1882939 ]
sgd.intercept_: [1.08752226e+09]


## Q9 to 11

In [206]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import Normalizer
from sklearn.neighbors import KNeighborsClassifier

In [210]:
X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [218]:
X_train = Normalizer().fit_transform(X_train)
X_test = Normalizer().fit_transform(X_test)

K = [2, 3, 4]

for k in K:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print('k:', k)
    print('Acc:', accuracy_score(y_test, y_pred))
#     if k == 3:
    print('f1:', f1_score(y_test, y_pred, average='weighted'))
    print('--------------------------------------------------')
    

k: 2
Acc: 0.9666666666666667
f1: 0.9671111111111111
--------------------------------------------------
k: 3
Acc: 0.9666666666666667
f1: 0.9671111111111111
--------------------------------------------------
k: 4
Acc: 0.9666666666666667
f1: 0.9671111111111111
--------------------------------------------------
