In [1]:
import numpy as np

from sklearn.datasets import fetch_california_housing

# PA 3

## Q1

In [2]:
california_housing = fetch_california_housing(as_frame=True)
df = california_housing.frame
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

## Q2

In [3]:
df = df.replace(r'^\s*$', np.nan, regex=True)
df.isna().sum().sum()

0

## Q3

In [4]:
from sklearn.model_selection import train_test_split

X, y = df.iloc[:,:-1], df['MedHouseVal']
# X, y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, shuffle=False)
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
16512  2.6368      34.0  5.769022   1.051630      1310.0  3.559783     37.72   
16513  3.6378      17.0  5.432075   1.022642      1802.0  3.400000     37.81   
16514  2.1186      28.0  4.707581   1.039711      1719.0  3.102888     37.80   
16515  2.1250      37.0  4.919431   1.052133       521.0  2.469194     37.80   
16516  2.9950      18.0  4.750988   0.984190      1531.0  3.025692     37.81   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
16512    -121.22  
16513    -121.22  
16514    -121.22  
16515    -121.22  
16516    -121.21  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[4128 rows x 8 columns]

## Q4

In [5]:
X_train

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
16507  4.4213      11.0  7.345936   1.132325      1605.0  3.034026     37.74   
16508  3.3578      35.0  5.450000   0.973529       958.0  2.817647     37.80   
16509  4.1833      22.0  6.564232   1.035264      1252.0  3.153652     37.76   
16510  3.4426       7.0  5.416393   1.028415      3006.0  3.285246     37.73   
16511  3.4009      22.0  6.214834   1.066496      1292.0  3.304348     37.76   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
16507    -121.11  
16508    -121.10  
16509    -121.11  
16510    -121.16  
16511    -121.25  

[16512 rows x 8 columns]

## Q5

In [6]:
y_train.describe()

count    16512.000000
mean         2.020670
std          1.135236
min          0.149990
25%          1.183000
50%          1.738000
75%          2.536000
max          5.000010
Name: MedHouseVal, dtype: float64

## Q6

In [17]:
y_test.describe()

count    4128.000000
mean        2.260110
std         1.207274
min         0.149990
25%         1.292000
50%         2.147500
75%         2.921000
max         5.000010
Name: MedHouseVal, dtype: float64

## Q7

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

lin_reg_pipeline = Pipeline([
    ('std_sclr', StandardScaler()),
    ('lin_reg', LinearRegression())
]) 

lin_reg_pipeline.fit(X_train, y_train)

lin_reg_pipeline[-1].coef_

array([ 0.83817967,  0.12032096, -0.32135834,  0.36456599, -0.00170674,
       -0.04524631, -0.87994217, -0.82634126])

## Q8

In [24]:
lin_reg_pipeline[-1].intercept_

2.020670313105614

# GA

## Q1

In [25]:
lin_reg_pipeline.score(X_test, y_test)

0.660514059153199

## Q2

In [34]:
from sklearn.metrics import mean_squared_error

y_test_predicted = lin_reg_pipeline.predict(X_test)

rmse = mean_squared_error(y_test, y_test_predicted, squared=False)
rmse

0.7033383507521879

## Q3

In [29]:
from sklearn.metrics import explained_variance_score

ev = explained_variance_score(y_test, y_test_predicted)
ev

0.6605500501742703

## Q4

In [31]:
from sklearn.metrics import max_error

me = max_error(y_test, y_test_predicted)
me

7.260453292958388

## Q5

In [33]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_test_predicted)
mae

0.516852699378704

## Q6

In [35]:
from sklearn.metrics import mean_squared_error

y_test_predicted = lin_reg_pipeline.predict(X_test)

mse = mean_squared_error(y_test, y_test_predicted, squared=True)
mse

0.49468483563880766

## Q7

In [37]:
from sklearn.linear_model import SGDRegressor

sgd_pipeline = Pipeline([
    ('featur_scaling', StandardScaler()),
    ('SGD', SGDRegressor(random_state=0))
])

sgd_pipeline.fit(X_train, y_train)
sgd_pipeline[-1].intercept_

array([2.01123921])

## Q8

In [38]:
sgd_pipeline[-1].coef_

array([ 0.84046697,  0.112331  , -0.41213039,  0.21595971, -0.01781887,
       -0.01480892, -0.87394103, -0.83913104])